#!/usr/bin/env python3
"""Regenerate construction_library_data.py from ASHRAE 90.1-2019 Table 5.5.

Source: ASHRAE Standard 90.1-2019 Tables 5.5-0 to 5.5-8 (building envelope
requirements by climate zone), as encoded in NREL openstudio-standards
(pinned tag below), the same edition and tag as the space-use defaults (#685):

  lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.construction_properties.json

Usage (fetches the file at the pinned tag unless a path is given):

  python scripts/build_construction_library.py [CONSTRUCTION_PROPERTIES_JSON]

Every value written is copied from one source row. IP values are verbatim;
SI U-factors and C-factors use 1 Btu/h-ft2-F = 5.678263 W/m2-K. F-factors are
kept in IP only.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

TAG = "v0.8.6"
TEMPLATE = "90.1-2019"
URL = (
    f"https://raw.githubusercontent.com/NREL/openstudio-standards/{TAG}/lib/openstudio-standards/"
    "standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.construction_properties.json"
)
U_IP_TO_SI = 5.678263  # 1 Btu/h-ft2-F = 5.678263 W/m2-K

CATEGORIES = ("Nonresidential", "Residential", "Semiheated")
SURFACES = (
    "ExteriorWall",
    "ExteriorRoof",
    "ExteriorFloor",
    "ExteriorWindow",
    "Skylight",
    "ExteriorDoor",
    "GlassDoor",
    "GroundContactFloor",
    "GroundContactWall",
)
OUT = Path(__file__).resolve().parent.parent / "construction_library_data.py"


def _load(path: str | None) -> list:
    if path:
        raw = Path(path).read_text()
    else:
        with urllib.request.urlopen(URL, timeout=60) as r:  # noqa: S310 (pinned https URL)
            raw = r.read().decode()
    return json.loads(raw)["construction_properties"]


def _si(v):
    return None if v is None else round(v * U_IP_TO_SI, 4)


def build(rows: list) -> dict:
    out = {}
    for r in rows:
        cat = r["building_category"]
        surf = r["intended_surface_type"]
        if cat not in CATEGORIES or surf not in SURFACES:
            continue
        cz = r["climate_zone_set"].replace("ClimateZone ", "").strip()
        key = (cat, cz, surf, r["standards_construction_type"])
        if key in out:
            raise SystemExit(f"duplicate source row for {key}")
        out[key] = {
            "source_construction": r["construction"],
            "u_ip": r["assembly_maximum_u_value"],
            "u_si": _si(r["assembly_maximum_u_value"]),
            "c_ip": r["assembly_maximum_c_factor"],
            "c_si": _si(r["assembly_maximum_c_factor"]),
            "f_ip": r["assembly_maximum_f_factor"],
            "shgc": r["assembly_maximum_solar_heat_gain_coefficient"],
            "min_vt_shgc": r["assembly_minimum_vt_shgc"],
        }
    return out


def render(table: dict) -> str:
    lines = [
        '"""Construction library: ASHRAE 90.1-2019 Table 5.5 maximum assembly values.',
        "",
        "GENERATED by scripts/build_construction_library.py -- do not edit by hand.",
        "",
        "Source:  ASHRAE Standard 90.1-2019, Tables 5.5-0 to 5.5-8",
        f"Encoded: NREL openstudio-standards {TAG} (template '{TEMPLATE}')",
        f"  {URL}",
        "",
        "Key: (building_category, climate_zone, surface, construction_type).",
        "u_ip / c_ip are Btu/h-ft2-F and f_ip is the F-factor, copied verbatim;",
        "u_si / c_si are W/m2-K (x 5.678263). None means the table gives no value.",
        '"""',
        "",
        "# ruff: noqa: E501  (generated table rows)",
        "# fmt: off",
        "SOURCE = 'ASHRAE Standard 90.1-2019, Table 5.5'",
        "EDITION = 'ASHRAE 90.1-2019'",
        f"SOURCE_VERSION = 'openstudio-standards {TAG}'",
        f"SOURCE_URL = {URL!r}",
        "",
        "CONSTRUCTION_LIBRARY = {",
    ]
    for key in sorted(table):
        lines.append(f"    {key!r}: {table[key]!r},")
    lines += ["}", "# fmt: on", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> None:
    table = build(_load(argv[1] if len(argv) > 1 else None))
    OUT.write_text(render(table))
    print(f"wrote {OUT.name}: {len(table)} rows")


if __name__ == "__main__":
    main(sys.argv)
