#!/usr/bin/env python3
"""Regenerate construction_library_prm_data.py from ASHRAE 90.1-2019 Table G3.4.

Source: ASHRAE Standard 90.1-2019 Normative Appendix G, Tables G3.4-1 to
G3.4-8 (Performance Rating Method baseline building envelope), as encoded in
NREL openstudio-standards (pinned tag below, the same tag as the Table 5.5
data, #747):

  lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm_2019/data/ashrae_90_1_prm_2019.construction_properties.json

Usage (fetches the file at the pinned tag unless a path is given):

  python scripts/build_prm_library.py [CONSTRUCTION_PROPERTIES_JSON]

Every value is copied from one source row. IP values are verbatim; SI
U-factors use 1 Btu/h-ft2-F = 5.678263 W/m2-K. F-factors stay in IP. Glazing
rows are banded by percent of surface (vertical: window-to-wall ratio,
skylight: skylight-to-roof ratio); each band is kept as its own row.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

TAG = "v0.8.6"
URL = (
    f"https://raw.githubusercontent.com/NREL/openstudio-standards/{TAG}/lib/openstudio-standards/"
    "standards/ashrae_90_1_prm/ashrae_90_1_prm_2019/data/"
    "ashrae_90_1_prm_2019.construction_properties.json"
)
U_IP_TO_SI = 5.678263
CATEGORIES = ("Nonresidential", "Residential", "Semiheated")
OUT = Path(__file__).resolve().parent.parent / "construction_library_prm_data.py"


def _load(path: str | None) -> list:
    if path:
        raw = Path(path).read_text()
    else:
        with urllib.request.urlopen(URL, timeout=60) as r:  # noqa: S310 (pinned https URL)
            raw = r.read().decode()
    return json.loads(raw)["construction_properties"]


def _si(v):
    return None if v is None else round(v * U_IP_TO_SI, 4)


def build(rows: list) -> dict:
    out: dict = {}
    for r in rows:
        cat = r["building_category"]
        if cat not in CATEGORIES:
            continue
        cz = r["climate_zone_set"].replace("ClimateZone ", "").strip()
        key = (cat, cz, r["intended_surface_type"], r["standards_construction_type"])
        row = {
            "source_construction": r["construction"],
            "pct_min": r["minimum_percent_of_surface"],
            "pct_max": r["maximum_percent_of_surface"],
            "u_ip": r["assembly_maximum_u_value"],
            "u_si": _si(r["assembly_maximum_u_value"]),
            "f_ip": r["assembly_maximum_f_factor"],
            "c_ip": r["assembly_maximum_c_factor"],
            "shgc": r["assembly_maximum_solar_heat_gain_coefficient"],
            "vt": r["assembly_minimum_visible_transmittance"],
        }
        bands = out.setdefault(key, [])
        if any((b["pct_min"], b["pct_max"]) == (row["pct_min"], row["pct_max"]) for b in bands):
            raise SystemExit(f"duplicate source row for {key} {row['pct_min']}-{row['pct_max']}")
        bands.append(row)
    for bands in out.values():
        bands.sort(key=lambda b: -1 if b["pct_min"] is None else b["pct_min"])
    return out


def render(table: dict) -> str:
    lines = [
        '"""Baseline envelope: ASHRAE 90.1-2019 Appendix G Table G3.4 (PRM 2019).',
        "",
        "GENERATED by scripts/build_prm_library.py -- do not edit by hand.",
        "",
        "Source:  ASHRAE Standard 90.1-2019, Appendix G Tables G3.4-1 to G3.4-8",
        f"Encoded: NREL openstudio-standards {TAG} (template '90.1-PRM-2019')",
        f"  {URL}",
        "",
        "Key: (building_category, climate_zone, surface, construction_type) -> list of",
        "rows, one per percent-of-surface band (pct_min/pct_max, None = any). u_ip and",
        "f_ip are copied verbatim; u_si is W/m2-K (x 5.678263).",
        '"""',
        "",
        "# ruff: noqa: E501  (generated table rows)",
        "# fmt: off",
        "SOURCE = 'ASHRAE Standard 90.1-2019, Appendix G Table G3.4'",
        "EDITION = 'ASHRAE 90.1-2019'",
        f"SOURCE_VERSION = 'openstudio-standards {TAG}'",
        f"SOURCE_URL = {URL!r}",
        "",
        "PRM_LIBRARY = {",
    ]
    for key in sorted(table):
        lines.append(f"    {key!r}: {table[key]!r},")
    lines += ["}", "# fmt: on", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> None:
    table = build(_load(argv[1] if len(argv) > 1 else None))
    OUT.write_text(render(table))
    print(f"wrote {OUT.name}: {len(table)} keys")


if __name__ == "__main__":
    main(sys.argv)
